### ISSUE TITLE
Client Request Pending

### ISSUE THREAD

**Issue by farhan787** [raghav4/ShortLink#5]
`Steps to reproduce:`

1. Type a url in the input box and click `shorten url` button.

`Current behaviour`: Client request is pending
`Expected behaviour`: should be the shortened url

**Comment by raghav4** [comment]
The Project is no longer deployed, thanks for reminding me, I'll pull it out. I might deploy it somewhere else. You can, however, try it out in your local machine.

Thanks @farhan787 .
